Document: termex
Title: Debian termex Manual
Author: <insert document author here>
Abstract: This manual describes what termex is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/termex/termex.sgml.gz

Format: postscript
Files: /usr/share/doc/termex/termex.ps.gz

Format: text
Files: /usr/share/doc/termex/termex.text.gz

Format: HTML
Index: /usr/share/doc/termex/html/index.html
Files: /usr/share/doc/termex/html/*.html

  
